version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "henderni"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
    groups:
      minecraft-apis:
        description: Minecraft API packages
        dependency-type: development
        patterns:
          - "@minecraft/*"
      build-tools:
        description: Build and compile tools
        dependency-type: development
        patterns:
          - "typescript"
